### PR TITLE
fix path label positioning in spacetimechart

### LINKED ISSUE #468: Train name isn't aligned with subpieces of its path
### What happened?

image
The train name isn't centered on the path that's visible. If there were some pieces of another train next to this one, one wouldn't be able to tell them apart

### What did you expect to happen?

I expect the name to not be completely out of the piece of path. For example, centered on the piece if it's too small

### How can we reproduce it (as minimally and precisely as possible)?

1. View a time table with many trains, some partially projected on the current path

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

Firefox

### LINKED ISSUE #529: Space-time chart: train name doesn't stick with the curve when scrolling the space axis
### What happened?

https://github.com/user-attachments/assets/3f59e468-9717-49ec-904c-7409c26ee65e

When scrolling along the time axis, the train name follows the curve. When scrolling the space axis, we lose the name of the train

### What did you expect to happen?

I expect the name of the train to stay visible as long as the curve is in the window.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to the deployed storybook
2. Zoom on the space axis, so there's room to scroll
3. Scroll on space axis
4. Witness

### On which environments the bug occurs?

Deployed Storybook

### On which browser the bug occurs?

Firefox

### PR DESCRIPTION
**Pull request by Synar**
Close #468
Close #529

### CODE REVIEW

File: ui-spacetimechart/src/components/PathLayer.tsx [hunk 1]
```diff
@@ -338,9 +369,21 @@ export const PathLayer = ({
       drawExtremities(ctx, stcContext);
 
       // Draw label:
-      if (!stcContext.hidePathsLabels) drawLabel(ctx, stcContext, path.label, color, segments);
+      if (!stcContext.hidePathsLabels) {
+        const pathLenght = computePathLength(stcContext.operationalPoints, segments);
```
Comment (clarani) [inline ui-spacetimechart/src/components/PathLayer.tsx]: Typo `pathLenght` => `pathLength` :wink:

**Review by clarani — APPROVED** [review]
LGTM, can you just rename your commits ? You're fixing the spacetimechart, and not the speedspacechart ;)

File: ui-spacetimechart/src/components/PathLayer.tsx (hunk 1 above)
Comment (Synar) [reply ui-spacetimechart/src/components/PathLayer.tsx]: Thanks!

**Comment by Synar** [comment]
Oops, will fix! '^^

**Review by kmer2016 — APPROVED** [review]
