### PR TITLE
ui-speedspacechart: fix speedlimittags layer blinking

### LINKED ISSUE #427: Speed space chart is blinking
### What happened?

Open all context information.
When we are moving the mouse over the speed space chart, it blinks. Same when we zoom in and out.

`Speed Limit Tag` is the most visible blinking component. 

### What did you expect to happen?

We should not see the chart blinking.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go [here](https://openrailassociation.github.io/osrd-ui/?path=/story/speedspacechart-rendering--speed-space-chart-default)
2. Open all context information.
3. Play around

### On which environments the bug occurs?

_No response_

### On which browser the bug occurs?

_No response_

### PR DESCRIPTION
**Pull request by Synar**
Close #427

There were 2 issues I could find leading to the blinking : 
- the store object was used as a dependency of useEffect, which means it was triggered every time
- the tooltip computation and the canvas drawing were tied together in a single function, despite the tooltip computation depending on the cursor position (and we don't want the canvas to be redrawn whenever the cursor moves)

There seems to be an overreliance on the store object in the code, but it may take a major refactor to fix it.

### CODE REVIEW

**Comment by Synar** [comment]
Close #427 on osrd-ui

Therefore fix half of https://github.com/OpenRailAssociation/osrd/issues/8853 on osrd

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 1]
```diff
@@ -82,108 +85,135 @@ export const drawSpeedLimitTags = async ({
     LINEAR_LAYERS_HEIGHTS.SPEED_LIMIT_TAGS_HEIGHT - LINEAR_LAYER_SEPARATOR_HEIGHT
   );
 
-  let tooltip: tooltipInfos | null = null;
+  if (speedLimitTags == undefined) return;
```
Comment (Yohh) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]:
```suggestion
  if (!speedLimitTags) return;
```

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 2]
```diff
@@ -82,108 +85,135 @@ export const drawSpeedLimitTags = async ({
...
+    };
+
+    const { tag } = value;
+    if (!(tag in tooltipTextMap)) continue;
+    const potential_tooltip_text = tooltipTextMap[tag];
+
+    const x = positionOnGraphScale(position.start, maxPosition, width, ratioX, MARGINS);
+    const nextBoundary = positionOnGraphScale(position.end!, maxPosition, width, ratioX, MARGINS);
+
+    if (nextBoundary == null || cursor.x == null || cursor.y == null) break;
```
Comment (Yohh) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]:
```suggestion
    if (nextBoundary === null || cursor.x === null || cursor.y === null) break;
```

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 3]
```diff
@@ -82,108 +85,135 @@ export const drawSpeedLimitTags = async ({
...
+  const { speedLimitTags, ratioX, leftOffset, cursor } = store;
+
+  const { MARGIN_TOP, MARGIN_LEFT } = MARGINS;
+
+  const maxPosition = maxPositionValue(store.speeds);
+
+  let tooltip: tooltipInfos | null = null;
 
-    return tooltip;
+  if (speedLimitTags == undefined) return null;
```
Comment (Yohh) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]:
```suggestion
  if (!speedLimitTags) return null;
```

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 4]
```diff
@@ -82,108 +85,135 @@ export const drawSpeedLimitTags = async ({
...
+        );
+
+        drawSvgImageWithColor(
+          ctx,
+          image,
+          iconXPosition + ICON_OFFSET,
+          iconYPosition + ICON_OFFSET,
+          ICON_WIDTH,
+          ICON_HEIGHT,
+          '#FFFFFF'
```
Comment (Yohh) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: nit: you could import { WHITE } from `const` then use it with `hex()` as in `reticle.ts`

**Review by Yohh — COMMENTED** [review]
very nice!

a few comments before reviewing deeper

**Comment by Yohh** [comment]
I can see a little unwanted space at the end of some rects, depending on the zoom level:
image

**Comment by Yohh** [comment]
I take the liberty of assigning @Caracol3 , he has a pending [PR](https://github.com/OpenRailAssociation/osrd-ui/pull/560) that will have many conflicts after this one

**Comment by Synar** [comment]
> I can see a little unwanted space at the end of some rects, depending on the zoom level:
> image
> 

Is this behavior that wasn't present before the pr? I tried not to touch the drawing code and dimension computations at all, so if something changed there I messed up

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 1 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Sure!

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 2 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Since == null matches exactly null and undefined and nothing else, this is actually the only case where I prefer == to ===. So I would rather keep it like this unless you insist.

**Comment by Yohh** [comment]
> > I can see a little unwanted space at the end of some rects, depending on the zoom level:
> 
> Is this behavior that wasn't present before the pr? I tried not to touch the drawing code and dimension computations at all, so if something changed there I messed up

you're right, it's not your work, that was already present

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 4 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Will do!

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx [hunk 5]
```diff
@@ -18,12 +18,44 @@ const SpeedLimitTagsLayer = ({ width, marginTop, store }: SpeedLimitTagsLayerPro
   const tooltip = useRef<tooltipInfos | null>();
 
   useEffect(() => {
-    const updateTooltip = async () => {
+    const updateCanvas = async () => {
       const currentCanvas = canvas.current as HTMLCanvasElement;
       const ctx = currentCanvas.getContext('2d') as CanvasRenderingContext2D;
-      tooltip.current = await drawSpeedLimitTags({ ctx, width, height: marginTop, store });
+      const restrictedStore = {
```
Comment (emersion) [inline ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: Hm, what is the purpose of creating an object containing a subset of `store` here? It seems like `drawSpeedLimitTags()` just pulls in part of these props anyways.

Note, TypeScript is pretty liberal when it comes to type compatibility for objects. This compiles just fine:

```ts
const obj = { foo: 42, bar: 43 };
type Foo = { foo: number };
const asdf: Foo = obj;
```

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx [hunk 6]
```diff
@@ -18,12 +18,44 @@ const SpeedLimitTagsLayer = ({ width, marginTop, store }: SpeedLimitTagsLayerPro
...
+          electricalProfiles: store.layersDisplay.electricalProfiles,
+          powerRestrictions: store.layersDisplay.powerRestrictions,
+        },
+        speeds: store.speeds,
+      };
+      await drawSpeedLimitTags({
+        ctx,
+        width,
+        height: marginTop,
+        store: restrictedStore as RestrictedStore,
```
Comment (emersion) [inline ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx]: I prefer to avoid `as` when possible, because it basically turns off the type checks. I don't think it's necessary here, `const restrictedStore: RestrictedStore = …` should work fine I believe (or just leave it up to type inference, should work too).

File: ui-speedspacechart/src/types/chartTypes.ts [hunk 7]
```diff
@@ -93,6 +93,20 @@ export type DrawFunctionParams = {
...
+> & {
+  layersDisplay: Pick<Store['layersDisplay'], 'electricalProfiles' | 'powerRestrictions'>;
+};
+
+export type RestrictedDrawFunctionParams = {
+  ctx: CanvasRenderingContext2D;
+  width: number;
+  height: number;
+  store: RestrictedStore;
+};
```
Comment (emersion) [inline ui-speedspacechart/src/types/chartTypes.ts]: Hm, I wonder if "restricted" is a good way to describe this. Is this going to be generally enough for any drawing function to re-use, or is this really specific to drawing speed limit tags, or a specific kind of layer?

Also not a fan of repeating the types… Do we really gain that much by narrowing the type here?

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 2 above)
Comment (Yohh) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: you're right, I just prefer to opt for the most restrictive when it's possible, it seems safer to me, but I don't want to look pyschorigid so as you wish

File: ui-speedspacechart/src/components/utils.ts [hunk 8]
```diff
@@ -23,23 +23,20 @@ export const getGraphOffsets = (width: number, height: number, declivities?: boo
...
- * @param store
+ * Given a list of speed data, return the maxSpeed
+ * @param speeds
  */
-export const maxSpeedValue = (store: Store) => {
-  const speeds = store.speeds;
-  return Math.max(...speeds.map(({ value }) => value));
-};
-
+export const maxSpeedValue = (speeds: LayerData<number>[]) =>
```
Comment (emersion) [inline ui-speedspacechart/src/components/utils.ts:29]: So, what is the motivation for changing the type here?

Is it to make it more obvious that only the `speeds` field from the store is used, so that callers can adjust their dependencies accordingly? 

(Would be nice to record this kind of info in the commit message :P )

**Comment by emersion** [comment]
> There were 2 issues I could find leading to the blinking

Next time, if you're feeling up for it, would be easier for reviewers if these two changes were split into separate commits!

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 2 above)
Comment (emersion) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: We try to avoid `==` because it has quite weird rules. In general, I go for `if (!thing)` instead of `if (thing == null)` (but `if (thing === null)` is fine by me as well).

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 9]
```diff
@@ -82,108 +85,135 @@ export const drawSpeedLimitTags = async ({
...
+    if (nextBoundary == null || cursor.x == null || cursor.y == null) break;
+
+    const tagWidth = nextBoundary - x - RECTANGLE_SPACING;
+    if (
+      cursor.x >= x - MARGIN_LEFT + leftOffset &&
+      cursor.x <= x - MARGIN_LEFT + leftOffset + tagWidth &&
+      cursor.y >= marginTop - MARGIN_TOP + Y_POSITION - 2 &&
+      cursor.y <= marginTop - MARGIN_TOP + Y_POSITION - 1 + RECT_HEIGHT
+    ) {
+      tooltip = {
```
Comment (emersion) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: I think we can straight up `return` here without the intermediate variable?

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 2 above)
Comment (Yohh) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: another way
```suggestion
    if (!nextBoundary || !cursor.x || !cursor.y) break;
```

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx (hunk 5 above)
Comment (Synar) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: Good catch. I think the code behaved the exact same before I did this, but I got an eslint warning because useEffect only contained a subset of the store and to the linter it looked like I was using all of the store. I changed a few things around since I got this linting error, so I will check again.

File: ui-speedspacechart/src/types/chartTypes.ts (hunk 7 above)
Comment (Synar) [reply ui-speedspacechart/src/types/chartTypes.ts]: I agree with you, the name is a bit imprecise, if I keep it I'll rename it.

The reason I did this was to be able to restrict what I fed to the canvas drawing function. I don't particularly enjoy this workaround either, so maybe I should fully remove the dependence of the drawing function on the store and its associated types and give it each of its arguments independently.

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 2 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: No, !x would be different here, because these are numbers, so x == null test if the value is nullish (only null and undefined) but !x tests if it's falsy, which includes values like 0

The equivalent would be x === null || x === undefined

Comment (Yohh) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: ah yes of course, my bad

Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Tbf I did this to avoid caring about whether they could be null or undefined, especially since in the previous version I think the type of one of them appeared like it could be neither null nor undefined, despite being tested. So perhaps I should actually investigate it instead of opting for the lazy way '^^

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 9 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Indeed we can, thanks

File: ui-speedspacechart/src/components/utils.ts (hunk 8 above)
Comment (Synar) [reply ui-speedspacechart/src/components/utils.ts:29]: Yes! The drawing function depends on this function, which depended on a fully populated store. So to decouple the first from the store, the second also needed to be decoupled.

Also I don't see why a function that computes things on an array and only depends on it should have any argument beyond the array in the first place

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx (hunk 6 above)
Comment (Synar) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx]: Ok, will do!

Comment (Synar) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx]: Ok so I hadn't constrained my type correctly with Pick, that's fixed

File: ui-speedspacechart/src/types/chartTypes.ts (hunk 7 above)
Comment (Synar) [reply ui-speedspacechart/src/types/chartTypes.ts]: To keep some consistency I have renamed and kept the type for now, but I think another pass to reduce the use of the store in all drawing functions could be appreciated. But this should probably be another pr.

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx (hunk 5 above)
Comment (Synar) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: Yeah still needed if we want the lint to pass. We could also deactivate this warning, but I do not dare do something like that.

**Comment by Synar** [comment]
> I take the liberty of assigning @Caracol3 , he has a pending [PR](https://github.com/OpenRailAssociation/osrd-ui/pull/560) that will have many conflicts after this one

Thanks! I'll confess I did not notice there was another PR on this component. But I don't mind being the one to do the conflict resolution

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx (hunk 5 above)
Comment (emersion) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: What is the linting error exactly?

Comment (Synar) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: calling await drawSpeedLimitTags({ctx, width, height: marginTop, store: store}) in the useEffect without an explicit store dependence (which we don't want, and neither do we want all of its attributes as dependences because that includes cursor) causes :

/home/alice/dev/osrd-ui/ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx
  32:6  warning  React Hook useEffect has a missing dependency: 'store'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 2 above)
Comment (emersion) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Yet another way, if you prefer:

```ts
typeof cursor.x === 'number'
```

File: ui-speedspacechart/src/components/utils.ts (hunk 8 above)
Comment (emersion) [reply ui-speedspacechart/src/components/utils.ts:29]: Makes sense!

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 10]
```diff
@@ -82,108 +86,132 @@ export const drawSpeedLimitTags = async ({
...
+  if (!speedLimitTags) return null;
+
+  for (const { position, value } of speedLimitTags) {
+    const tooltipTextMap: Record<string, string> = {
+      incompatible: 'Incompatible with the infrastructure',
+    };
+
+    const { tag } = value;
+    if (!(tag in tooltipTextMap)) continue;
+    const potential_tooltip_text = tooltipTextMap[tag];
```
Comment (emersion) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Style nit: we're using camelCase. Probably could be simply named `text` since that's the name of the field below.

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts [hunk 11]
```diff
@@ -82,108 +86,132 @@ export const drawSpeedLimitTags = async ({
...
+  const { speedLimitTags, ratioX, leftOffset, cursor } = store;
+
+  const { MARGIN_TOP, MARGIN_LEFT } = MARGINS;
+
+  const maxPosition = maxPositionValue(store.speeds);
+
+  if (!speedLimitTags) return null;
+
+  for (const { position, value } of speedLimitTags) {
+    const tooltipTextMap: Record<string, string> = {
```
Comment (emersion) [inline ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts:189]: Sounds a bit weird to have an object with just a single entry, and I don't think an explicit type is required here, but I don't mind too much.

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx (hunk 5 above)
Comment (emersion) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: ACK. Could be simplified a tad with `pick()` from lodash, but I'm fine with the current logic.

File: ui-speedspacechart/src/types/chartTypes.ts [hunk 12]
```diff
@@ -93,6 +93,20 @@ export type DrawFunctionParams = {
   setStore?: React.Dispatch<React.SetStateAction<Store>>;
 };
 
+export type SpeedLimitTagsLayerDrawingStore = Pick<
+  Store,
+  'speedLimitTags' | 'ratioX' | 'leftOffset' | 'speeds'
+> & {
+  layersDisplay: Pick<Store['layersDisplay'], 'electricalProfiles' | 'powerRestrictions'>;
```
Comment (emersion) [inline ui-speedspacechart/src/types/chartTypes.ts:100]: Question: do we really need to optimize the case where the user updates the visibility of a layer other than these two?

Just wondering if it's really worth the more involved type and picking.

File: ui-speedspacechart/src/types/chartTypes.ts (hunk 7 above)
Comment (emersion) [reply ui-speedspacechart/src/types/chartTypes.ts]: The new name looks good to me!

**Review by emersion — COMMENTED** [review]
I'm mostly nitpicking at this point. Feel free to discard/ignore comments you disagree with.

File: ui-speedspacechart/src/types/chartTypes.ts (hunk 12 above)
Comment (Synar) [reply ui-speedspacechart/src/types/chartTypes.ts:100]: Honestly not really, but I still did this in order to avoid having non primary types in the useEffect dependency array

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 11 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts:189]: I'll confess I didn't look at the tooltip code at all, but I'll do

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 10 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Sure, same as below

File: ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx (hunk 5 above)
Comment (Synar) [reply ui-speedspacechart/src/components/layers/SpeedLimitTagsLayer.tsx:24]: I wish.
Doing something like
```js
const restrictedStore = {
        ...pick(store, ['speedLimitTags', 'ratioX', 'leftOffset', 'speeds']),
        layersDisplay: pick(store.layersDisplay, ['electricalProfiles', 'powerRestrictions']),
        };
```
still leads to the same linting issue, as the linter does not particularly care to know what pick does, it only sees that store is used somewhere in the function. I'm sure there is some way to sidestep this issue, perhaps with useMemo, but it's not immediatly obvious to me

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 11 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts:189]: Ah no I thought you were talking about something else but I remember now

Due to how the code was structured I assumed there might be tooltips added for other tags in the future, and I wanted for their addition to be as smooth as possible, without nested if conditions like were present in the previous version of the code.

And some type indication is needed for potentialTooltipText to later know it is a string (even though I agree the ts engine should have been able to deduce that by itself)

File: ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts (hunk 10 above)
Comment (Synar) [reply ui-speedspacechart/src/components/helpers/drawElements/speedLimitTags.ts]: Fixed ^^

**Review by emersion — APPROVED** [review]
