### PR TITLE
ui-spacetimechart: picking layer downscaling

### LINKED ISSUE #915: space time chart: picking only covers a portion of the stage when devicePixelRatio < 1
### What happened?

https://github.com/user-attachments/assets/54f111d3-36c3-4327-bc42-f0a6d9af373e

When `devicePixelRatio < 1`, the picking layer only covers a related fraction of the stage. The video shows for instance that paths hovering only works in the top left quadrant of the stage, and does not work on the right or on the bottom.

### What did you expect to happen?

Interactions should work similarly on the whole stage all the time.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to [this page](https://openrailassociation.github.io/osrd-ui/?path=/story/spacetimechart-paths-interactions--default-args)
2. Zoom out in your browser (with `Ctrl` + `-` for instance)
3. Try interacting with the paths in the bottom right of the stage

### On which environments the bug occurs?

Local Storybook

### On which browser the bug occurs?

Firefox

### PR DESCRIPTION
**Pull request by jacomyal**
This commit fixes #915, and also improves picking performances, by downscaling the picking layer.

Details:
- Cleans unused and poorly named "number" argument from drawAliasedLine
- Adds new get getPickingScalingRatio helper, that returns the picking downscaling ratio depending on the current devicePixelRatio value
- Fixes picking layers resize handling
- Adds a new optional "scalingRatio" argument to each canvas aliased drawing function
- Adds new scalingRatio argument to PickingDrawingFunction, and updates useCanvas accordingly
- Gives the scaling ratio from PickingDrawingFunction to aliased functions in every places where usePicking is called

### CODE REVIEW

File: ui-spacetimechart/src/utils/canvas.ts [hunk 1]
```diff
@@ -139,8 +174,13 @@ export function drawAliasedDisc(
...
+  drawOnBottom: boolean,
+  scalingRatio: number = 1
 ): void {
+  centerX = Math.round(centerX * scalingRatio);
+  centerY = Math.round(centerY * scalingRatio);
+  radius = Math.round(radius * scalingRatio);
+
   centerX = Math.round(centerX);
   centerY = Math.round(centerY);
   radius = Math.ceil(radius);
```
Comment (emersion) [inline ui-spacetimechart/src/utils/canvas.ts]: These seem unnecessary now?

File: ui-spacetimechart/src/utils/canvas.ts [hunk 2]
```diff
@@ -2,54 +2,89 @@ import { clamp, identity } from 'lodash';
...
-    return drawAliasedLine(imageData, to, from, [r, g, b], thickness, drawOnBottom);
+  if (fromX > toX)
+    return drawAliasedLine(
+      imageData,
+      { x: toX, y: toY },
+      { x: fromX, y: fromY },
+      [r, g, b],
+      thickness,
+      drawOnBottom
+    );
```
Comment (emersion) [inline ui-spacetimechart/src/utils/canvas.ts]: We should probably pass down the `scalingRatio` here?

File: ui-spacetimechart/src/utils/canvas.ts [hunk 3]
```diff
@@ -139,8 +174,13 @@ export function drawAliasedDisc(
   { x: centerX, y: centerY }: Point,
   radius: number,
   [r, g, b]: RGBColor | RGBAColor,
-  drawOnBottom: boolean
+  drawOnBottom: boolean,
+  scalingRatio: number = 1
 ): void {
+  centerX = Math.round(centerX * scalingRatio);
+  centerY = Math.round(centerY * scalingRatio);
+  radius = Math.round(radius * scalingRatio);
```
Comment (emersion) [inline ui-spacetimechart/src/utils/canvas.ts]: Old code was using `Math.ceil` here, do we want to retain the old behavior?

I don't have the full context, but maybe it's to avoid ending up with `radius = 0`?

File: ui-spacetimechart/src/utils/canvas.ts (hunk 2 above)
Comment (jacomyal) [reply ui-spacetimechart/src/utils/canvas.ts]: Oh good catch, thanks! Fixed :+1:

File: ui-spacetimechart/src/utils/canvas.ts (hunk 3 above)
Comment (jacomyal) [reply ui-spacetimechart/src/utils/canvas.ts]: Yes, the `Math.ceil` was here for this reason, and I kind of brainfarted here I think. Anyway, it's cleaner now.

File: ui-spacetimechart/src/utils/canvas.ts (hunk 1 above)
Comment (jacomyal) [reply ui-spacetimechart/src/utils/canvas.ts]: I merged the two parts and restored the `Math.ceil` call.

**Review by emersion — APPROVED** [review]
LGTM!

File: ui-spacetimechart/src/utils/canvas.ts [hunk 4]
```diff
@@ -2,54 +2,90 @@ import { clamp, identity } from 'lodash';
...
+
+  // When devicePixelRatio is over 1 (like for Retina displays), we downscale based on the "HTML
+  // pixels":
+  if (dpr > 1) return PICKING_DOWNSCALING_RATIO;
+
+  // When devicePixelRatio is under 1 (like when the user zooms out for instance), we downscale
+  // based on the actual "screen pixels" (to avoid having a too large scene to fill):
+  if (dpr < 1) return PICKING_DOWNSCALING_RATIO * dpr;
+
+  return PICKING_DOWNSCALING_RATIO;
```
Comment (clarani) [inline ui-spacetimechart/src/utils/canvas.ts]:
```suggestion
  // When devicePixelRatio is over 1 (like for Retina displays), we downscale based on the "HTML
  // pixels":
  if (dpr >= 1) return PICKING_DOWNSCALING_RATIO;

  // When devicePixelRatio is under or equal to 1 (like when the user zooms out for instance), we downscale
  // based on the actual "screen pixels" (to avoid having a too large scene to fill):
  return PICKING_DOWNSCALING_RATIO * dpr;
```

**Review by clarani — COMMENTED** [review]
LGTM :white_check_mark: 

Only left 1 small comment

**Review by clarani — APPROVED** [review]

File: ui-spacetimechart/src/utils/canvas.ts (hunk 4 above)
Comment (jacomyal) [reply ui-spacetimechart/src/utils/canvas.ts]: I just integrated that modification, thanks!
