### PR TITLE
ui-spacetimechart: fix time labels, graduations and captions

### LINKED ISSUE #10688: time graduation off by 1 or 2 hour
Time axis should show 00 06 12. 01, 07, 13 make no sense
Image

largest vertical line should be midnight

Image

### LINKED ISSUE #10689: Space time chart time caption is off
Image

### PR DESCRIPTION
**Pull request by anisometropie**
closes https://github.com/OpenRailAssociation/osrd/issues/10688
closes https://github.com/OpenRailAssociation/osrd/issues/10689

### CODE REVIEW

File: ui-spacetimechart/src/utils/canvas.ts [hunk 1]
```diff
@@ -273,3 +273,39 @@ export function drawPathExtremity(
...
+
+export function displayElementsBasedOnZoom<T>(
+  minT: number,
+  maxT: number,
+  timeRanges: number[],
+  levels: number[],
+  formatter: (level: number, i: number) => T = identity
+) {
+  const result: Record<number, T> = {};
+  const localOffset = -new Date(minT).getTimezoneOffset() * 60 * 1000;
```
Comment (emersion) [inline ui-spacetimechart/src/utils/canvas.ts]: In general I'm not a fan of using `getTimezoneOffset()`, because it behaves wrongly on timezone offset change. For instance if daylight savings are applied on the left side of the chart but aren't on the right side, the chart will be wrong.

But it's not the end of the world here, since it's just about graduations.

I'd suggest applying the offset only to `minT` since it's the only timestamp it's valid for:

```ts
const localOffset = new Date(minT).getTimezoneOffset() * 60 * 1000;
let t = Math.floor((minT - localOffset) / range) * range + localOffset;
```

then the condition inside the loop can be dropped, and all other `localOffset` operations can be removed.

(By the way, maybe `minTLocalOffset` may be a more descriptive name to make it clear that it's only valid for `minT`.)

File: ui-spacetimechart/src/utils/canvas.ts [hunk 2]
```diff
@@ -273,3 +273,39 @@ export function drawPathExtremity(
...
+ * Keys are times in ms
+ * Values are the highest level on each time
+ */
+
+export function displayElementsBasedOnZoom<T>(
+  minT: number,
+  maxT: number,
+  timeRanges: number[],
+  levels: number[],
+  formatter: (level: number, i: number) => T = identity
```
Comment (emersion) [inline ui-spacetimechart/src/utils/canvas.ts:293]: I'd prefer to apply this as a second step (ie, the caller can do it) to reduce the complexity of that function. (The docs seem outdated.)

File: ui-spacetimechart/src/utils/canvas.ts [hunk 3]
```diff
@@ -273,3 +273,39 @@ export function drawPathExtremity(
...
+ * @param minT number timestamp
+ * @param maxT number timestamp
+ * @param timeRanges time frames (24h, 12h, 6h, …)
+ * @param gridlinesLevels width of the lines for each time frame
+ * @returns Record<number, number>
+ * Keys are times in ms
+ * Values are the highest level on each time
+ */
+
+export function displayElementsBasedOnZoom<T>(
```
Comment (emersion) [inline ui-spacetimechart/src/utils/canvas.ts]: I wonder if we could find a better name of this function.

The function itself doesn't deal with the zoom so it sounds a bit weird to mention it there.

Maybe `computeMarksFromTimeLevels()`?

File: ui-spacetimechart/src/stories/lib/components.tsx [hunk 4]
```diff
@@ -83,7 +83,7 @@ const DataLabel = ({
         </>
       ) : (
         <>
-          <div>Time: {new Date(data.time).toLocaleTimeString('en-GB', { timeZone: 'UTC' })}</div>
+          <div>Time: {new Date(data.time).toLocaleTimeString()}</div>
```
Comment (emersion) [inline ui-spacetimechart/src/stories/lib/components.tsx:86]: Good catch!

File: ui-spacetimechart/src/utils/canvas.ts (hunk 3 above)
Comment (anisometropie) [reply ui-spacetimechart/src/utils/canvas.ts]: `computeVisibleTimeMarkers` ?

File: ui-spacetimechart/src/utils/canvas.ts (hunk 1 above)
Comment (anisometropie) [reply ui-spacetimechart/src/utils/canvas.ts]: that issue existed already, we have days with only 23h or 25h, everything becomes shifted, because we add 86400 s each time.

thanks, it’s neater like this.
Why do we need the offset inside the Math.floor ?
I think `let t = Math.floor(minT / range) * range - minTLocalOffset;` is enough.

File: ui-spacetimechart/src/utils/canvas.ts (hunk 2 above)
Comment (anisometropie) [reply ui-spacetimechart/src/utils/canvas.ts:293]: we have to use Object.entries / re map over the object / Object.fromEntries
this seems way more cumbersome than passing a simple formatter

File: ui-spacetimechart/src/utils/canvas.ts (hunk 3 above)
Comment (emersion) [reply ui-spacetimechart/src/utils/canvas.ts]: Works for me!

File: ui-spacetimechart/src/utils/canvas.ts (hunk 1 above)
Comment (emersion) [reply ui-spacetimechart/src/utils/canvas.ts]: My reasoning is that all timestamps are Unix time without any offset. If we apply the offset once without undoing it, then it's not Unix time anymore, or am I missing something?

Maybe the `Math.floor()` makes it so we get the correct number by chance if we apply the offset only once? However I think it'd break on other `range` and offset values.

File: ui-spacetimechart/src/utils/canvas.ts (hunk 2 above)
Comment (emersion) [reply ui-spacetimechart/src/utils/canvas.ts:293]: `mapValues` from lodash makes this less cumbersome, FWIW.

(But I'm not feeling strongly about this.)

File: ui-spacetimechart/src/utils/canvas.ts (hunk 1 above)
Comment (anisometropie) [reply ui-spacetimechart/src/utils/canvas.ts]: We’re still getting a valid unix time. But instead of getting the timestamp of 0h UTC we get the timestamp of 22h UTC (so that it shows 0h Paris and not 2h Paris like before)

Not sure why it works with the offset applied twice to be quite frank

image_50353153

File: ui-spacetimechart/src/utils/canvas.ts (hunk 2 above)
Comment (anisometropie) [reply ui-spacetimechart/src/utils/canvas.ts:293]: think i’m gonna stick with the original idea, `mapValues` doesn’t keep the indices

File: ui-spacetimechart/src/utils/canvas.ts (hunk 1 above)
Comment (emersion) [reply ui-spacetimechart/src/utils/canvas.ts]: Sorry, I still don't believe it's correct. `minT` is the earliest timestamp in the time window. We want to find the first graduation marker. We need to snap `minT` to a `range`-spaced grid shifted by the offset. Everything needs to be UTC apart from the snapping.

Your solution works as long as `minTLocalOffset` is negative, because the loop keeps going until it reaches `maxT` (it'll just run longer). However, it breaks with positive timezone offsets. You can try e.g. `minTLocalOffset = 6 * 60 * 60 * 1000` and notice missing grid lines on the left.

Comment (anisometropie) [reply ui-spacetimechart/src/utils/canvas.ts]: Ok I see the issue, we get `t` snapped to 0h local time in both case;
but we sometimes get 0h off by one day, so we miss some of the range, thanks for digging that up ! 

I’ve written a test to take that case into account

Comment (emersion) [reply ui-spacetimechart/src/utils/canvas.ts]: Sweet, thanks for adding a test!

**Review by emersion — APPROVED** [review]
LGTM!

**Comment by emersion** [comment]
Typo: "up-spacetimechart: fix time graduation" (should be "ui-", not "up-")
