### PR TITLE
Slider fixes

### LINKED ISSUE #10598: slider keyboard behavior
ui-core slider, Fix changing committed value with tab + keyboard arrows. 

(https://github.com/OpenRailAssociation/osrd/issues/9722#issuecomment-2554091943)

### LINKED ISSUE #10599: Slider left side styling
slider track left/right side colors https://github.com/OpenRailAssociation/osrd/issues/9722#issuecomment-2554091943

### LINKED ISSUE #10621: firefox slider discrepancy due to thumb size
https://github.com/user-attachments/assets/606ecdc9-393b-49fb-8baa-7c187c083911

### PR DESCRIPTION
**Pull request by anisometropie**
### fix committed value
closes https://github.com/OpenRailAssociation/osrd/issues/10598

### left/right styling
closes https://github.com/OpenRailAssociation/osrd/issues/10599

rest https://www.sketch.com/s/ca1f66cf-046d-4992-ae63-62187269ba7e/v/mGRKq9/a/0A3RkWj#Inspect
active https://www.sketch.com/s/ca1f66cf-046d-4992-ae63-62187269ba7e/v/mGRKq9/a/oMmnEJj#Inspect
focus (using tab) https://www.sketch.com/s/ca1f66cf-046d-4992-ae63-62187269ba7e/v/mGRKq9/a/lReWJEv#Inspect
hover https://www.sketch.com/s/ca1f66cf-046d-4992-ae63-62187269ba7e/v/mGRKq9/a/kK4bZjD#Inspect

### firefox insanity (committed value off by 1)
https://github.com/OpenRailAssociation/osrd/issues/9722#issuecomment-2626869201
#closes https://github.com/OpenRailAssociation/osrd/issues/10621

### CODE REVIEW

File: ui-core/src/components/inputs/Slider.tsx [hunk 1]
```diff
@@ -38,12 +38,16 @@ const Slider = ({
...
 
-  const handleMouseUp = (e: MouseEvent<HTMLInputElement>) => {
+  const handleCommit = (e: MouseEvent<HTMLInputElement> | KeyboardEvent<HTMLInputElement>) => {
     if (onChangeCommitted) {
       onChangeCommitted(e);
     }
   };
 
+  const visualMin = Number(min) - 5;
+  const visualMax = Number(max) + 5;
```
Comment (SharglutDev) [inline ui-core/src/components/inputs/Slider.tsx]: Could be nice to explain the "magic number" 5 (if I understand correctly it's for the case when the slider is active and the round part is smaller)

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested, good job ! You can resolve the last comment after fixing it.

There is just one weird behavior (not related to this PR), maybe we can discuss it with @thibautsailly : when dragging the slider with the mouse, as the thumb is smaller, I can never reach the beginning/end of the range track

File: ui-core/src/components/inputs/Slider.tsx (hunk 1 above)
Comment (anisometropie) [reply ui-core/src/components/inputs/Slider.tsx]: done!
