### PR TITLE
ui-speedspacechart: fix display issues when the GEV is integrated in OSRD

### LINKED ISSUE #253: ui-speedspacechart: some elements arn't well displayed while integrating the GEV in OSRD
- [x] when a linear layer is displayed, the chart doesn't resize inclunding his height
- [x] the front-interractivity-layer style 'mr-2' has to be removed
- [x] the settings panel should adapt his height to the component height
- [x] speedLimits and temporarySpeedLimits checkboxes should be disable

### PR DESCRIPTION
**Pull request by Yohh**
- add setHeight props in SpeedSpaceChart, set it with dynamicHeight
- adapt the story in .tsx to use a useState() hook
- remove mt-2 useless tailwind rule for front-interractivity-layer
- calculate the settings panel height by using the SpeedSpaceChart height
- disable speedLimits and temporarySpeedLimits checkboxes
- add missing type: 'non_electrified' in ElectrifictationValues

close #253

### CODE REVIEW

File: ui-speedspacechart/src/components/SpeedSpaceChart.tsx [hunk 1]
```diff
@@ -145,6 +147,11 @@ const SpeedSpaceChart = ({
     }
   }, [data]);
 
+  useEffect(() => {
+    setHeight(dynamicHeight);
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, [store.layersDisplay]);
+
```
Comment (Uriel-Sautron) [inline ui-speedspacechart/src/components/SpeedSpaceChart.tsx]:
```suggestion
  useEffect(() => {
    setHeight(dynamicHeight);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [dynamicHeight]);

```

File: ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx [hunk 2]
```diff
@@ -1,7 +1,8 @@
+import React, { useState } from 'react';
 import type { Meta, StoryObj } from '@storybook/react';
 import '@osrd-project/ui-core/dist/theme.css';
 import '@osrd-project/ui-speedspacechart/dist/theme.css';
-import SpeedSpaceChart from '../components/SpeedSpaceChart';
+import SpeedSpaceChart, { SpeedSpaceChartProps } from '../components/SpeedSpaceChart';
```
Comment (Uriel-Sautron) [inline ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx]:
```suggestion
import SpeedSpaceChart, { type SpeedSpaceChartProps } from '../components/SpeedSpaceChart';
```

File: ui-speedspacechart/src/components/SpeedSpaceChart.tsx (hunk 1 above)
Comment (Yohh) [reply ui-speedspacechart/src/components/SpeedSpaceChart.tsx]: done

File: ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx (hunk 2 above)
Comment (Yohh) [reply ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx]: done

File: ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx [hunk 3]
```diff
@@ -16,19 +17,58 @@ const data = formatData(
...
+  translations,
+}: SpeedSpaceChartProps) => {
+  const [containerHeight, setContainerHeight] = useState(521.5);
+
+  useEffect(() => {
+    setContainerHeight(height);
+  }, [height]);
+
+  return (
+    <div style={{ height: containerHeight }}>
```
Comment (SharglutDev) [inline ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx:34]: Should we have a minHeight after which we consider we can't exploit the chart anymore ?

File: ui-speedspacechart/src/components/utils.ts [hunk 4]
```diff
@@ -108,6 +109,13 @@ export const getLinearLayerMarginTop = (
   return height + adjustment - MARGINS.MARGIN_BOTTOM;
 };
 
+export const getLinearLayersDisplayedHeight = (layersDisplay: Store['layersDisplay']) =>
+  [
+    layersDisplay.electricalProfiles ? LINEAR_LAYERS_HEIGHTS.ELECTRICAL_PROFILES_HEIGHT : 0,
+    layersDisplay.powerRestrictions ? LINEAR_LAYERS_HEIGHTS.POWER_RESTRICTIONS_HEIGHT : 0,
+    layersDisplay.speedLimitTags ? LINEAR_LAYERS_HEIGHTS.SPEED_LIMIT_TAGS_HEIGHT : 0,
+  ].reduce((acc, curr) => acc + curr, 0);
+
```
Comment (SharglutDev) [inline ui-speedspacechart/src/components/utils.ts:114]: Instead of creating this new function, could you use `getAdaptiveHeight` function and pass it 0 for the initial height ? I think this would give the same result.

File: ui-speedspacechart/src/components/layers/FrontInteractivityLayer.tsx [hunk 5]
```diff
@@ -23,7 +23,7 @@ const FrontInteractivityLayer = ({
   return (
     <canvas
       id="front-interactivity-layer"
-      className="absolute ml-10 mt-2"
+      className="absolute ml-10"
```
Comment (SharglutDev) [inline ui-speedspacechart/src/components/layers/FrontInteractivityLayer.tsx]: It seems like the ml-10 is erased by the `margin-left: 3rem;` in `#front-interactivity-layer`.

I don't see any difference if I remove `ml-10`

**Review by SharglutDev — CHANGES_REQUESTED** [review]
Thank you for these changes, left some comments

File: ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx (hunk 3 above)
Comment (Yohh) [reply ui-speedspacechart/src/stories/SpeedSpaceChart.stories.tsx:34]: in OSRD yes, but for any other user it all depends about what is displayed

File: ui-speedspacechart/src/components/utils.ts (hunk 4 above)
Comment (Yohh) [reply ui-speedspacechart/src/components/utils.ts:114]: I think I prefer use it in `getAdaptiveHeight` instead of set a 0, how do you feel with it?

Comment (Yohh) [reply ui-speedspacechart/src/components/utils.ts:114]: done

File: ui-speedspacechart/src/components/layers/FrontInteractivityLayer.tsx (hunk 5 above)
Comment (Yohh) [reply ui-speedspacechart/src/components/layers/FrontInteractivityLayer.tsx]: done

**Review by SharglutDev — APPROVED** [review]
Lgtm and tested
