### PR TITLE
ui-speedspacechart: fix reticle display when no hover

### LINKED ISSUE #10666: front: the tooltip remains diplayed on the GEV even when the cursor leaves the component
### What happened?

The tooltip remains displayed when the cursor leaves the component via the left, top or bottom: this hinders screen copying and communication with clients

### PR DESCRIPTION
**Pull request by RomainValls**
close https://github.com/OpenRailAssociation/osrd/issues/10666 😈

### CODE REVIEW

File: ui-speedspacechart/src/components/layers/ReticleLayer.tsx [hunk 1]
```diff
@@ -24,6 +24,8 @@ const ReticleLayer = ({ width, height, heightOffset, store }: ReticleLayerProps)
     if (store.cursor.y && store.cursor.y < maxCursorHeight) {
       const detailsBox = drawCursor({ ctx, width, height, store });
       setTrainDetails(detailsBox || null);
+    } else {
+      setTrainDetails(null);
     }
```
Comment (kmer2016) [inline ui-speedspacechart/src/components/layers/ReticleLayer.tsx]: You can also clear th reticle using the `clearCanvas` function that you can import from `../utils` too
```suggestion
    } else {
      clearCanvas(ctx, width, height);
      setTrainDetails(null);
    }
```

**Review by kmer2016 — COMMENTED** [review]
Thank you for the fix. Very small suggestion ;)

File: ui-speedspacechart/src/components/layers/ReticleLayer.tsx (hunk 1 above)
Comment (RomainValls) [reply ui-speedspacechart/src/components/layers/ReticleLayer.tsx]: thanks 👍

**Review by kmer2016 — APPROVED** [review]
LGTM !
