### PR TITLE
Speedspacechart fix curves

### LINKED ISSUE #8333: Front: Speed space chart is broken when there is no stop at the end
### What happened?

When we put no stop at the end, the GEV is broken : 

Image

### What did you expect to happen?

We should have a correct GEV

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a TrainSchedule
2. Remove the stop at the end

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Google Chrome

### OSRD version (top right corner `Account` button > `Informations`)

staging 0a34296

### PR DESCRIPTION
**Pull request by flomonster**
Curve drawing doesn't work when the train starts at non-zero speed/ends at non-zero speed.

fixes https://github.com/OpenRailAssociation/osrd/issues/8333

## Before

image

## After

image

### CODE REVIEW

**Comment by Yohh** [comment]
be careful, `ctx.globalCompositeOperation` purpose was to be able to display the declivities under the curves, removing it totally hides them:
[globalCompositeOperation](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation)


image

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts [hunk 1]
```diff
@@ -42,27 +47,29 @@ export const drawCurve = ({ ctx, width, height, store }: DrawFunctionParams) =>
...
   const maxPosition = maxPositionValue(store);
 
-  ctx.lineWidth = 0.5;
-  ctx.fillStyle = 'rgba(17, 101, 180, 0.02)';
-  ctx.strokeStyle = 'rgb(17, 101, 180, 0.5)';
-
   ctx.beginPath();
-  drawSpecificCurve({ maxSpeed, maxPosition, ratioX }, { width, height, ctx }, speeds);
-  ctx.closePath();
+  ctx.fillStyle = 'rgba(17, 101, 180, 0.02)';
```
Comment (SharglutDev) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts:63]: No chroma for the colors in this file ?

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts [hunk 2]
```diff
@@ -9,10 +9,11 @@ import { clearCanvas, maxPositionValue, maxSpeedValue } from '../../utils';
 
 const { CURVE_MARGIN_TOP, CURVE_MARGIN_SIDES } = MARGINS;
 
-const drawSpecificCurve = (
+const traceCurve = (
   curveConfig: CurveConfig,
   canvasConfig: CanvasConfig,
-  specificSpeeds: LayerData<number>[]
+  specificSpeeds: LayerData<number>[],
+  closePath: boolean
```
Comment (SharglutDev) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: Even though it's in the same file, we recently decided to use an object when passing a boolean in a function param so it can be more explicit why we call i with `true` or `false`

```suggestion
  { closePath: boolean }
```

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts
Comment (SharglutDev) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts:1]: Not sure to understand why do we pass from 2 traceCurve to 4 ?

Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts:1]: Ideally, I would call the function twice. The issue is to draw a shape with borders using different styles. Please let me know if you know how to do so.

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts (hunk 1 above)
Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts:63]: I did not change anything yet. I will adapt curve colors in a future PR.

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts (hunk 2 above)
Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: Okay... Is it optimized during the JS transformation?
It's something that the code editor should handle.

Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: Fixed here: https://github.com/OpenRailAssociation/osrd-ui/pull/509/commits/0e65f5a6a56c0fa79afce0a8271343676bbb2945.

I'm really not a big fan of this convention. What about putting the boolean into a viriable instead of buildign a record?

Comment (SharglutDev) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: Ah sorry for the confusion, I wasn't very clear maybe. The goal was to use the function like the following in osrd for example : 
`export function secToHoursString(sec: number | null, { withSeconds = false } = {}): TimeString {...}`

and then use it like that when calling the function : 
`secToHoursString(durationInSecond, { withSeconds: true })`

Is it ok for you ?

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts
Comment (SharglutDev) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts:1]: Don't think of something different but maybe we can add a comment for each step or to explain the purpose of using them twice each ?

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts (hunk 2 above)
Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: In my case I have one variable and I don't want a default value to it. I don't see how do you want me handle this.

> [!NOTE]
> Making the function arguments more explicit seems like a good idea, but it makes the function declaration less readable.

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts [hunk 3]
```diff
@@ -42,27 +41,39 @@ export const drawCurve = ({ ctx, width, height, store }: DrawFunctionParams) =>
...
+  ctx.beginPath();
+  ctx.lineWidth = 0.5;
+  ctx.strokeStyle = 'rgb(17, 101, 180, 0.5)';
+  traceCurve({ width, height, ctx }, { maxSpeed, maxPosition, ratioX, isClosePath: false }, speeds);
   ctx.stroke();
 
+  ctx.beginPath();
   ctx.fillStyle = 'rgba(255, 255, 255)';
-  ctx.strokeStyle = 'rgb(17, 101, 180)';
+  ctx.strokeStyle = 'rgba(0, 0, 0, 0)';
```
Comment (jacomyal) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: This line should be unnecessary I think, since in this part you only call `ctx.fill`, and `strokeStyle` will be reset later, before calling `ctx.stroke.`

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts [hunk 4]
```diff
@@ -1,34 +1,33 @@
...
 import { MARGINS } from '../../const';
 import { clearCanvas, maxPositionValue, maxSpeedValue } from '../../utils';
 
 const { CURVE_MARGIN_TOP, CURVE_MARGIN_SIDES } = MARGINS;
 
-const drawSpecificCurve = (
-  curveConfig: CurveConfig,
+const traceCurve = (
   canvasConfig: CanvasConfig,
+  curveConfig: { maxSpeed: number; maxPosition: number; ratioX: number; isClosePath: boolean },
```
Comment (jacomyal) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: `isClosePath` sounds weird to me. I'd rather name that `closePath`, `doClosePath` or `isPathClosed`.

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts [hunk 5]
```diff
@@ -42,27 +41,39 @@ export const drawCurve = ({ ctx, width, height, store }: DrawFunctionParams) =>
   const maxSpeed = maxSpeedValue(store);
   const maxPosition = maxPositionValue(store);
 
-  ctx.lineWidth = 0.5;
-  ctx.fillStyle = 'rgba(17, 101, 180, 0.02)';
-  ctx.strokeStyle = 'rgb(17, 101, 180, 0.5)';
-
+  // Curves must be drawn twice one for the fill and one for the stroke
```
Comment (jacomyal) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts:57]: You can draw the curve only once, if you do the things in this order:
- Describe curve path (with `moveTo` and `lineTo`)
- Draw the curve (with `stroke`)
- Close the path (with the last `lineTo` calls and `closePath`)
- Fill the curve (with `fill`)

You can see an example here:
https://codesandbox.io/p/sandbox/d367fh?file=%2Fsrc%2Findex.mjs

Comment (Yohh) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts:57]: if you fill after stroke, the area filled will partially overlap the stroke, right?

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts (hunk 3 above)
Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: Done

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts (hunk 4 above)
Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: I removed this parameter.

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts (hunk 5 above)
Comment (flomonster) [reply ui-speedspacechart/src/components/helpers/drawElements/curve.ts:57]: Indeed. It doesn't seem possible to do this in one pass.

> [!NOTE]
> I did a little optimization. Now, x/y points positions are computed only once and reuse for the stroke.

File: ui-speedspacechart/src/components/helpers/drawElements/curve.ts [hunk 6]
```diff
@@ -1,34 +1,35 @@
...
+import type { DrawFunctionParams, LayerData } from '../../../types/chartTypes';
 import { MARGINS } from '../../const';
 import { clearCanvas, maxPositionValue, maxSpeedValue } from '../../utils';
 
 const { CURVE_MARGIN_TOP, CURVE_MARGIN_SIDES } = MARGINS;
 
-const drawSpecificCurve = (
-  curveConfig: CurveConfig,
-  canvasConfig: CanvasConfig,
+const curvePoints = (
```
Comment (SharglutDev) [inline ui-speedspacechart/src/components/helpers/drawElements/curve.ts]: Feels weird to have a function named like a const. It could be `computeCurvePoints` or something like that ?

**Review by SharglutDev — APPROVED** [review]
Lgtm
