### PR TITLE
front: fix combo box input props change

### LINKED ISSUE #9302: front: the stdcm form is not completly reset when clicking on "Effectuer une nouvelle requête"
### What happened?

When I reset the stdcm form, the form is reset in the store, but the inputs are not emptied. 

### What did you expect to happen?

The fields should be emptied, otherwise, I think that they are still filled.

### How can we reproduce it (as minimally and precisely as possible)?

1. Go to stdcm, launch a request
2. Select the simulation
3. Click on reset the form
4. The form is still filled but you can see that the rollingStock image has disappeared

### On which environments the bug occurs?

Recette (SNCF)

### On which browser the bug occurs?

Firefox

### OSRD version (top right corner `Account` button > `Informations`)

.

### PR DESCRIPTION
**Pull request by Wadjetz**
fix [#9302](https://github.com/OpenRailAssociation/osrd/issues/9302)

### CODE REVIEW

File: ui-core/src/components/inputs/ComboBox/ComboBox.tsx [hunk 1]
```diff
@@ -80,15 +80,26 @@ const ComboBox = <T,>({
...
+    clearInputValue();
     focusInput();
   };
 
+  /* eslint-disable react-hooks/exhaustive-deps */
+  useEffect(() => {
+    if (!value) {
+      clearInputValue();
+    }
+  }, [value]);
```
Comment (clarani) [inline ui-core/src/components/inputs/ComboBox/ComboBox.tsx]: Can you modify the existing hook line 120 instead of adding a new one ?
Also, why do you call clearInputValue ? setValue(value) is not enough ?:thinking:

**Review by clarani — APPROVED** [review]
LGTM, tested in osrd :white_check_mark:
